#!/usr/bin/env bash
NODE_ENV=production DATABASE_HOST=ds117866.mlab.com DATABASE_PORT=17866 DATABASE_NAME=store-cms DATABASE_USERNAME=duynhat DATABASE_PASSWORD=duynhat2019 DATABASE_AUTHENTICATION_DATABASE=store-cms PORT=5555 npm start
